image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build-production
  - build-development
  
build-production:
  stage: build-production
  script:
    - echo -e $APP_ENV > .env.local
    - cat .env.local
    - docker build -f Dockerfile.prod -t cafrotos/jsf_webapp .
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push cafrotos/jsf_webapp
  only: 
    - master

build-development:
  stage: build-development
  script:
    - echo -e $APP_ENV > .env.local
    - cat .env.local
    - docker build -f Dockerfile.dev -t cafrotos/jsf_webapp_dev .
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push cafrotos/jsf_webapp_dev
  only: 
    - develop