FROM node:12 as builder

WORKDIR /app

COPY . /app

RUN yarn

RUN REACT_APP_SERVER_ENV=production yarn build

FROM nginx:alpine

WORKDIR /app

COPY --from=builder /app/build /app

COPY nginx/nginx-production.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && sed -i -e 's/$API_ENDPOINT/'"$API_ENDPOINT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'