export const AUTHENCATION = "AUTHENCATION"

export const CHECK_LOGIN = "CHECK_LOGIN"
export const LOGIN_LOADING = "LOGIN_LOADING"
export const LOGIN_SUCCSESS = "LOGIN_SUCCSESS"
export const LOGIN_FALSE = "LOGIN_FALSE"

export const FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID = "FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID"
export const FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID_LOADING = "FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID_LOADING"
export const FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID_SUCCSESS = "FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID_SUCCSESS"
export const FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID_ERROR = "FETCH_LIST_SHIPMENT_BY_WAREHOUSE_ID_ERROR"

export const FETCH_LIST_CLIENT = "FETCH_LIST_CLIENT"
export const FETCH_LIST_CLIENT_LOADING = "FETCH_LIST_CLIENT_LOADING"
export const FETCH_LIST_CLIENT_SUCCSESS = "FETCH_LIST_CLIENT_SUCCSESS"
export const FETCH_LIST_CLIENT_ERROR = "FETCH_LIST_CLIENT_ERROR"

export const FETCH_LIST_PACKAGE_BY_SHIPMENT_ID = "FETCH_LIST_PACKAGE_BY_SHIPMENT_ID"
export const FETCH_LIST_PACKAGE_BY_SHIPMENT_ID_LOADING = "FETCH_LIST_PACKAGE_BY_SHIPMENT_ID_LOADING"
export const FETCH_LIST_PACKAGE_BY_SHIPMENT_ID_SUCCSESS = "FETCH_LIST_PACKAGE_BY_SHIPMENT_ID_SUCCSESS"
export const FETCH_LIST_PACKAGE_BY_SHIPMENT_ID_ERROR = "FETCH_LIST_PACKAGE_BY_SHIPMENT_ID_ERROR"

export const FETCH_LIST_PACKAGE_BY_SHIPPER_ID = "FETCH_LIST_PACKAGE_BY_SHIPPER_ID"
export const FETCH_LIST_PACKAGE_BY_SHIPPER_ID_LOADING = "FETCH_LIST_PACKAGE_BY_SHIPPER_ID_LOADING"
export const FETCH_LIST_PACKAGE_BY_SHIPPER_ID_SUCCSESS = "FETCH_LIST_PACKAGE_BY_SHIPPER_ID_SUCCSESS"
export const FETCH_LIST_PACKAGE_BY_SHIPPER_ID_ERROR = "FETCH_LIST_PACKAGE_BY_SHIPPER_ID_ERROR"

export const FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID = "FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID"
export const FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID_LOADING = "FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID_LOADING"
export const FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID_SUCCSESS = "FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID_SUCCSESS"
export const FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID_ERROR = "FETCH_LIST_PACKAGE_BY_WAREHOUSE_ID_ERROR"

export const UPDATE_CHECKBOX_LIST_PACKAGE_BY_WAREHOUSE_ID = "UPDATE_CHECKBOX_LIST_PACKAGE_BY_WAREHOUSE_ID"

export const UPDATE_CHECKBOX_LIST_PACKAGE_BY_SHIPPER_ID = "UPDATE_CHECKBOX_LIST_PACKAGE_BY_SHIPPER_ID"

export const UPDATE_CHECKBOX_LIST_PACKAGE_BY_SHIPMENT_ID = "UPDATE_CHECKBOX_LIST_PACKAGE_BY_SHIPMENT_ID"

export const UPDATE_PACKAGE_STATUS = "UPDATE_PACKAGE_STATUS"
export const UPDATE_PACKAGE_STATUS_SUCCSESS = "UPDATE_PACKAGE_STATUS_SUCCSESS"
export const UPDATE_PACKAGE_STATUS_ERROR = "UPDATE_PACKAGE_STATUS_ERROR"

export const FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID = "FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID"
export const FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID_LOADING = "FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID_LOADING"
export const FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID_SUCCSESS = "FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID_SUCCSESS"
export const FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID_ERROR = "FETCH_LIST_SHIPPER_BY_WAREHOUSE_ID_ERROR"

export const FILTER = "FILTER"

export const GET_FILTER_BUTTON = "GET_FILTER_BUTTON"
export const GET_FILTER_BUTTON_SUCCSESS = "GET_FILTER_BUTTON_SUCCSESS"

export const UPDATE_PACKAGE_DETAIL = "UPDATE_PACKAGE_DETAIL"
export const UPDATE_PACKAGE_DETAIL_LOADING = "UPDATE_PACKAGE_DETAIL_LOADING"
export const UPDATE_PACKAGE_DETAIL_SUCCSESS = "UPDATE_PACKAGE_DETAIL_SUCCSESS"
export const UPDATE_PACKAGE_DETAIL_ERROR = "UPDATE_PACKAGE_DETAIL_ERROR"

export const UPDATE_COD_RECEIVED = "UPDATE_COD_RECEIVED"
export const UPDATE_COD_RECEIVED_LOADING = "UPDATE_COD_RECEIVED_LOADING"
export const UPDATE_COD_RECEIVED_SUCCSESS = "UPDATE_COD_RECEIVED_SUCCSESS"
export const UPDATE_COD_RECEIVED_ERROR = "UPDATE_COD_RECEIVED_ERROR"

export const FETCH_PACKAGE_DONE_BY_SHIPPER_ID = "FETCH_PACKAGE_DONE_BY_SHIPPER_ID"
export const FETCH_PACKAGE_DONE_BY_SHIPPER_ID_LOADING = "FETCH_PACKAGE_DONE_BY_SHIPPER_ID_LOADING"
export const FETCH_PACKAGE_DONE_BY_SHIPPER_ID_SUCCSESS = "FETCH_PACKAGE_DONE_BY_SHIPPER_ID_SUCCSESS"
export const FETCH_PACKAGE_DONE_BY_SHIPPER_ID_ERROR = "FETCH_PACKAGE_DONE_BY_SHIPPER_ID_ERROR"

export const FETCH_REASON = "FETCH_REASON"
export const FETCH_REASON_LOADING = "FETCH_REASON_LOADING"
export const FETCH_REASON_SUCCSESS = "FETCH_REASON_SUCCSESS"
export const FETCH_REASON_ERROR = "FETCH_REASON_ERROR"

export const UPDATE_STATUS_SHIPMENT = "UPDATE_STATUS_SHIPMENT"
export const UPDATE_STATUS_SHIPMENT_LOADING = "UPDATE_STATUS_SHIPMENT_LOADING"
export const UPDATE_STATUS_SHIPMENT_SUCSSESS = "UPDATE_STATUS_SHIPMENT_SUCSSESS"
export const UPDATE_STATUS_SHIPMENT_ERROR = "UPDATE_STATUS_SHIPMENT_ERROR"

export const FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE = "FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE"
export const FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE_LOADING = "FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE_LOADING"
export const FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE_SUCCSESS = "FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE_SUCCSESS"
export const FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE_ERROR = "FETCH_PACKAGE_BY_SHIPMENT_ID_QRCODE_ERROR"

export const FETCH_DETAIL_WALLET_SHIPPER = "FETCH_DETAIL_WALLET_SHIPPER"
export const FETCH_DETAIL_WALLET_SHIPPER_LOADING = "FETCH_DETAIL_WALLET_SHIPPER_LOADING"
export const FETCH_DETAIL_WALLET_SHIPPER_SUCCSESS = "FETCH_DETAIL_WALLET_SHIPPER_SUCCSESS"
export const FETCH_DETAIL_WALLET_SHIPPER_ERROR = "FETCH_DETAIL_WALLET_SHIPPER_ERROR"


